language: ruby

rvm:
  - 2.2.0

before_script:
  # - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test
  - bundle exec rake db:reset
  # - bundle exec rake db:test:prepare --trace
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - bundle exec rake spec
  - bundle exec cucumber
